In [37]:
# Add our dependencies
import csv
import os
import pandas as pd
import numpy as py

In [38]:
# Read in CSV file and print as a DataFrame
highestgrossers_original_df = pd.read_csv('Resources/HighestGrossers.csv')
highestgrossers_original_df.head()

,YEAR,MOVIE,GENRE,MPAA RATING,DISTRIBUTOR,TOTAL FOR YEAR,TOTAL IN 2019 DOLLARS,TICKETS SOLD
0,1995,Batman Forever,Drama,PG-13,Warner Bros.,"$184,031,112","$387,522,978","4,23,06,002"
1,1996,Independence Day,Adventure,PG-13,20th Century Fox,"$306,169,255","$634,504,608","6,92,69,062"
2,1997,Men in Black,Adventure,PG-13,Sony Pictures,"$250,650,052","$500,207,943","5,46,07,854"
3,1998,Titanic,Adventure,PG-13,Paramount Pictures,"$443,319,081","$865,842,808","9,45,24,324"
4,1999,Star Wars Ep. I: The Phantom Menace,Adventure,PG,20th Century Fox,"$430,443,350","$776,153,749","8,47,32,942"

In [39]:
highestgrossers_original_df.tail()

,YEAR,MOVIE,GENRE,MPAA RATING,DISTRIBUTOR,TOTAL FOR YEAR,TOTAL IN 2019 DOLLARS,TICKETS SOLD
22,2017,Star Wars Ep. VIII: The Last Jedi,Action,PG-13,Walt Disney,"$517,218,368","$528,173,936","5,76,60,910"
23,2018,Black Panther,Action,PG-13,Walt Disney,"$700,059,566","$703,901,821","7,68,45,177"
24,2019,Avengers: Endgame,NaN,PG-13,Walt Disney,"$858,373,000","$858,373,002","9,37,08,843"
25,2020,Bad Boys For Life,NaN,R,Sony Pictures,"$204,417,855","$204,417,848","2,23,16,359"
26,2021,Shang-Chi and the Legend of the Ten Rings,NaN,PG-13,Walt Disney,"$224,226,704","$224,226,704","2,44,78,897"

In [40]:
highestgrossers_clean_df = highestgrossers_original_df

In [41]:
highestgrossers_clean_df.tail()

,YEAR,MOVIE,GENRE,MPAA RATING,DISTRIBUTOR,TOTAL FOR YEAR,TOTAL IN 2019 DOLLARS,TICKETS SOLD
22,2017,Star Wars Ep. VIII: The Last Jedi,Action,PG-13,Walt Disney,"$517,218,368","$528,173,936","5,76,60,910"
23,2018,Black Panther,Action,PG-13,Walt Disney,"$700,059,566","$703,901,821","7,68,45,177"
24,2019,Avengers: Endgame,NaN,PG-13,Walt Disney,"$858,373,000","$858,373,002","9,37,08,843"
25,2020,Bad Boys For Life,NaN,R,Sony Pictures,"$204,417,855","$204,417,848","2,23,16,359"
26,2021,Shang-Chi and the Legend of the Ten Rings,NaN,PG-13,Walt Disney,"$224,226,704","$224,226,704","2,44,78,897"

In [42]:
highestgrossers_clean_df.fillna("Action", inplace=True)

In [43]:
highestgrossers_clean_df.tail()

,YEAR,MOVIE,GENRE,MPAA RATING,DISTRIBUTOR,TOTAL FOR YEAR,TOTAL IN 2019 DOLLARS,TICKETS SOLD
22,2017,Star Wars Ep. VIII: The Last Jedi,Action,PG-13,Walt Disney,"$517,218,368","$528,173,936","5,76,60,910"
23,2018,Black Panther,Action,PG-13,Walt Disney,"$700,059,566","$703,901,821","7,68,45,177"
24,2019,Avengers: Endgame,Action,PG-13,Walt Disney,"$858,373,000","$858,373,002","9,37,08,843"
25,2020,Bad Boys For Life,Action,R,Sony Pictures,"$204,417,855","$204,417,848","2,23,16,359"
26,2021,Shang-Chi and the Legend of the Ten Rings,Action,PG-13,Walt Disney,"$224,226,704","$224,226,704","2,44,78,897"

In [44]:
highestgrossers_clean_df.head()

,YEAR,MOVIE,GENRE,MPAA RATING,DISTRIBUTOR,TOTAL FOR YEAR,TOTAL IN 2019 DOLLARS,TICKETS SOLD
0,1995,Batman Forever,Drama,PG-13,Warner Bros.,"$184,031,112","$387,522,978","4,23,06,002"
1,1996,Independence Day,Adventure,PG-13,20th Century Fox,"$306,169,255","$634,504,608","6,92,69,062"
2,1997,Men in Black,Adventure,PG-13,Sony Pictures,"$250,650,052","$500,207,943","5,46,07,854"
3,1998,Titanic,Adventure,PG-13,Paramount Pictures,"$443,319,081","$865,842,808","9,45,24,324"
4,1999,Star Wars Ep. I: The Phantom Menace,Adventure,PG,20th Century Fox,"$430,443,350","$776,153,749","8,47,32,942"

In [45]:
# Export to CSV
highestgrossers_clean_df.to_csv("Resources/HighestGrossers_Clean.csv")